In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from block.models.networks.fusions.fusions import Tucker

In [4]:
k = torch.tensor([[[1,2,3,4,5,6],[7,8,9,10,11,12],[10,20,30,40,50,60],[7,8,9,10,11,12],[1,2,3,4,5,6],[10,20,30,40,50,60]],[[1,2,3,4,5,6],[10,20,30,40,50,60],[1,2,3,4,5,6],[7,8,9,10,11,12],[10,20,30,40,50,60],[7,8,9,10,11,12]]]); k

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [10, 20, 30, 40, 50, 60],
         [ 7,  8,  9, 10, 11, 12],
         [ 1,  2,  3,  4,  5,  6],
         [10, 20, 30, 40, 50, 60]],

        [[ 1,  2,  3,  4,  5,  6],
         [10, 20, 30, 40, 50, 60],
         [ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [10, 20, 30, 40, 50, 60],
         [ 7,  8,  9, 10, 11, 12]]])

In [5]:
j = k.view(-1, k.size(-1))

In [7]:
j.view(2,6,6)

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [10, 20, 30, 40, 50, 60],
         [ 7,  8,  9, 10, 11, 12],
         [ 1,  2,  3,  4,  5,  6],
         [10, 20, 30, 40, 50, 60]],

        [[ 1,  2,  3,  4,  5,  6],
         [10, 20, 30, 40, 50, 60],
         [ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [10, 20, 30, 40, 50, 60],
         [ 7,  8,  9, 10, 11, 12]]])

In [82]:
k = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12],[1,2,3,4,5,6],[7,8,9,10,11,12],[1,2,3,4,5,6],[7,8,9,10,11,12]]); k

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [83]:
m = torch.tensor([0,1,0,0,1,0], dtype=torch.uint8);m

tensor([0, 1, 0, 0, 1, 0], dtype=torch.uint8)

In [84]:
h = torch.tensor([[1,1,2,3,2,2],[3,4,5,3,4,5]])

In [85]:
k.t().masked_scatter(m, h.t()).t()

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 1,  1,  2,  3,  2,  2],
        [ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 3,  4,  5,  3,  4,  5],
        [ 7,  8,  9, 10, 11, 12]])

In [67]:
j[:,1,:]

tensor([[ 7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [5]:
input_dim = 512
output_dim = 512
tucker = Tucker((input_dim, input_dim), output_dim, mm_dim=100, shared=False)

In [6]:
in_ = torch.FloatTensor(10, 100, input_dim)
out_ = torch.FloatTensor(10, 100, input_dim)

In [7]:
final = tucker([in_, out_])

In [8]:
final.shape

torch.Size([10, 100, 512])

In [9]:
attn = torch.matmul(in_, final.permute(0,2,1)).sum(-1)

In [10]:
attn.shape

torch.Size([10, 100])

In [11]:
attn = F.softmax(attn, -1).unsqueeze(-1)

In [12]:
in_ = (in_ * attn)

In [13]:
in_.shape

torch.Size([10, 100, 512])

In [14]:
ln = nn.LayerNorm(output_dim, eps=1e-12)

In [15]:
ln(in_).shape

torch.Size([10, 100, 512])

Argument inputs (works in JUPYTER environment ONLY)

In [9]:
len(data['dico'].id2word)

52654

In [8]:
torch.LongTensor(2,4).fill_(1)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [12]:
np.concatenate(haha, haha[:3])

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
np.array(list(haha) + list(haha[:r]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [18]:
g.image_features[[1,2,2]]

TypeError: Indexing elements must be in increasing order

In [12]:
g = data['cross_modal'][('cap','img')]['coco36']['train']

In [15]:
sent = (np.append(sent[0], np.zeros((sent[0].shape[0], r))

torch.Size([32])

In [12]:
self.data = np.append(self.image_features[a:self.n_regions], 
                      np.zeros((r, self.image_features.shape[-1])), 
                      axis=0)

torch.Size([2048, 1184])

In [11]:
h = torch.randn(10,2,100)
k = torch.randn(10,5,100)

jj = torch.cat((h, k), dim=1); jj.shape

torch.Size([10, 7, 100])

In [10]:
print(f"[mask] x_cap shape: {x[0].shape}")
print(f"[mask] x_img shape: {x[1].shape}")
print(f"[mask] y_cap shape: {y_cap.shape}")
print(f"[mask] y_img shape: {y_img.shape}")
print(f"[mask] _x_candidates_img shape: {_x_candidates_img.shape}")
print(f"[mask] pred_mask_cap shape: {pred_mask[0].shape}")
print(f"[mask] pred_mask_img shape: {pred_mask[1].shape}")

[mask] x_cap shape: torch.Size([10, 32])
[mask] x_img shape: torch.Size([37, 32, 2048])
[mask] y_cap shape: torch.Size([48])
[mask] y_img shape: torch.Size([184])
[mask] _x_candidates_img shape: torch.Size([184, 2048])
[mask] pred_mask_cap shape: torch.Size([10, 32])
[mask] pred_mask_img shape: torch.Size([37, 32])


In [ ]:
import numpy as np
d = np.argsort([1,3,5,6], kind='mergesort')
l = np.array([2,3,4,2])

In [ ]:
l[d]

In [ ]:
next(data['caption_stream']['coco36']['train'].get_iterator(True))[0].shape

In [ ]:
next(data['caption_stream']['coco36']['train'].get_iterator(True))[1]

In [ ]:
word = []
for i in k:
    word.append(data['dico'].id2word[i.item()])

In [ ]:
' '.join(word)

In [ ]:
len(word)

In [ ]:
torch.arange(10).reshape(2,-1)

In [ ]:
import numpy as np
h = np.arange(24).transpose(6,-1); h

In [ ]:
h = h.view(2, 3, -1); h

In [ ]:
h = h.transpose(0,1); h[:,0,:]

In [ ]:
next(data['cross_modal'][('cap','img')]['coco36']['train'].get_iterator(True))[1].shape

In [ ]:
params

In [ ]:
np.array_equal(data.image_features[3363], data.image_features[list(tmp_sorted_imgids)][tmp_sorted_ids][30])

In [ ]:
data.image_ids

In [ ]:
haha = next(data.get_iterator(shuffle=True))

print(f'Sentence: {haha[0][0].size()}')
print(f'Image: {haha[1].size()}')
print(f'Spatial: {haha[2].size()}')

In [ ]:
next(data.get_iterator(shuffle=True))[0][:,4]

In [ ]:
import numpy as np

g = np.array_split([2,3,4,2,2,2,3,4], 4)
np.random.shuffle(g);g

In [ ]:
import h5py

valid_features = h5py.File('./data/image/coco36/valid.hdf5', 'r')
train = h5py.File('./data/image/coco36/train_features.hdf5', 'r')

with open('./data/image/coco36/train_genome_dets.json', 'r') as j:
    train_id = json.load(j)

In [ ]:
valid_features['image_features'][4815]

In [ ]:
train_id

In [ ]:
train['image_features'][0]

In [ ]:
train_features['image_features'].shape

In [ ]:
print(f"[cap, img] x_cap shape: {x[0].shape}")
print(f"[cap, img] x_img shape: {x[1].shape}")
print(f"[cap, img] spatial_x_cap: {spatial_x[0]}")
print(f"[cap, img] spatial_x_img shape: {spatial_x[1].shape}")
print(f"[cap, img] lengths_cap shape: {lengths[0].shape}")
print(f"[cap, img] lengths_img shape: {lengths[1].shape}")
print(f"[cap, img] positions shape: {positions.shape}")
print(f"[cap, img] modality shape: {modality.shape}")

In [ ]:
print(f"[cap] x shape: {x.shape}")
print(f"[cap] spatial_x: {spatial_x}")
print(f"[cap] lengths shape: {lengths.shape}")
print(f"[cap] positions shape: {positions}")
print(f"[cap] modality shape: {modality.shape}")

In [ ]:
print(f"[ipm] x shape: {x.shape}")
print(f"[ipm] spatial_x shape: {spatial_x.shape}")
print(f"[ipm] lengths shape: {lengths.shape}")
print(f"[ipm] positions shape: {positions}")
print(f"[ipm] imgs: {imgs}")

In [ ]:
print(f"[img] x shape: {x.shape}")
print(f"[img] spatial_x shape: {spatial_x.shape}")
print(f"[img] lengths shape: {lengths.shape}")
print(f"[img] positions shape: {positions}")
print(f"[img] modality shape: {modality.shape}")

In [ ]:
print(f"train_features: {len(train_features['image_features'])}")
print(f"valid_features: {len(valid_features['image_features'])}")
print(f"test_features: {len(test_features['image_features'])}")

In [ ]:
train_captions = torch.load("./data/image/coco36/processed_cap/train.cap.en.pth")

In [ ]:
train_dataset = data['image_stream']['coco36']['train']
valid_dataset = data['image_stream']['coco36']['valid']

In [ ]:
len(train_dataset.objdet)

In [ ]:
len(valid_dataset.train_features)

In [ ]:
h = [('cap', None), ('img', None), ('cap', 'img')]

In [ ]:
h = (1,2,3,4)
h[::-1]

In [ ]:
positions = torch.arange(20)[:, None].repeat(1, 32)

In [ ]:
positions[5:,0] -= 5

In [ ]:
positions

In [ ]:
from tqdm import tqdm

image_features = []

for _,train_index in tqdm(enumerate(train_dataset.objdet)):
    if (train_index[0] == "v"):
        image_features.append(train_dataset.train_features[train_index[1]]) 
    if (train_index[0] == "t"):
        image_features.append(valid_dataset.train_features[train_index[1]])

In [ ]:
np.random.choice([2,3,2,5,7])

In [ ]:
x.new(256).long().shape

In [ ]:
positions = x.new(256).long()
positions = torch.arange(256, out=positions).unsqueeze(0)

In [ ]:
positions.shape

In [ ]:
data['image_stream']['coco36']['train'].train_features.shape

In [ ]:
data['image_stream']['coco36']['train'].spatial_features[0]

In [ ]:
haha = torch.tensor([1,2,3])

In [ ]:
haha[haha ==]

In [ ]:
stream = data['caption_stream']['coco36']['train']

In [ ]:
stream.data.shape

In [ ]:
import numpy as np
np.zeros(10)

In [ ]:
np.zeros(10) + params.eos

In [ ]:
214529 * 32

In [ ]:
from tqdm import tqdm

for _, pos in tqdm(enumerate(data['positions'][:10])):
    for i in data['sentences'][pos[0]:pos[1]]:
        print(data['dico'].id2word[i])

In [ ]:
trainer.data['dico'].counts['chin']

In [ ]:
import numpy as np
haha = np.array(list(data['dico'].counts))
# print((np.maximum(haha, 1)**0)[params.pad_index])
print(haha)

In [ ]:
haha = [l1 for l1, l2 in params.mlm_steps if l2 is None]

In [ ]:
[haha[i] for i in np.random.choice(len(haha), size=min(5, len(haha)), p=None, replace=True)] if len(haha) > 0 else []

In [ ]:
print(1000 ** -0.8)
print(10 ** -0.8)

In [ ]:
import numpy as np

x = torch.randn(4, 2, 2) ; x

In [ ]:
m = torch.zeros(4, 2).byte()
m[1,0] = 1.
m[2,1] = 1.; m

In [ ]:
m = m.unsqueeze(-1).expand_as(x); m.shape

In [ ]:
x[m].view(-1, 2)

In [ ]:
h = x.reshape(2,4,-1);h

In [ ]:
h.transpose(0,1)

In [ ]:
h.shape

In [ ]:
perm = np.random.permutation(x.shape[0])
perm = torch.from_numpy(perm);perm

In [ ]:
x[perm]

In [ ]:
alen = torch.arange(256, dtype=torch.long)
mask = alen < lengths[:, None]

In [ ]:
prod = x[mask]; prod

In [ ]:
prod[1] = 1

In [ ]:
prods = torch.multinomial(torch.FloatTensor([0.8,0.1,0.1]), len(prod), replacement=True)

In [ ]:
prods

In [ ]:
x = torch.randn(32).fill_(256).type(torch.LongTensor) ; x

In [ ]:
import torchvision.models as models
resblock = models.resnet50(pretrained=True)

In [ ]:
import numpy as np

x = trainer.x
all_regions = x.size()[0] # n_bbox * n_features
pred_mask = np.random.rand(all_regions) <= 0.15
pred_mask = torch.from_numpy(pred_mask.astype(np.uint8))

pred_mask[torch.sum(x, dim=-1) == 0] = 0

In [ ]:
y = torch.rand(3,4); y

In [ ]:
y.t()

In [ ]:
y_mask = torch.zeros(3).byte(); y_mask.shape

In [ ]:
y_mask[[0,2]] = 1; y_mask

In [ ]:
y_re = torch.rand(2,4); y_re

In [ ]:
y_re.shape

In [ ]:
y.t().masked_scatter(y_mask, y_re.t()).t()

In [ ]:
pred_mask.shape

In [ ]:
ha = torch.tensor([1,4,2,4,5,6,3])

In [ ]:
leng = len(x[np.random.choice(all_regions, _x_real.shape[0])])

In [ ]:
probs = torch.multinomial(torch.FloatTensor([0.8, 0.1, 0.1]), leng, replacement=True)

In [ ]:
probs = probs.unsqueeze(-1)

In [ ]:
probs

In [ ]:
probs == 0

In [ ]:
print(len(haha[haha==0]))
print(len(haha[haha==1]))
print(len(haha[haha==2]))

In [ ]:
_x_real = x[pred_mask]
_x_real[:10]

In [ ]:
_x_rand = x[np.random.choice(all_regions, _x_real.shape[0])]
_x_mask = _x_real.clone().fill_(1)

In [ ]:
_x_mask.shape

In [ ]:
_x = _x_mask * (probs == 0).float() + _x_real * (probs == 1).float() + _x_rand * (probs == 2).float()

In [ ]:
_x.shape

In [ ]:
pred_probs = torch.FloatTensor([params.word_mask, params.word_keep, params.word_rand]); pred_probs

In [ ]:
pred_mask[8]

In [ ]:
pred_mask[10]

In [ ]:
# x = trainer.x

print(x[8])
print(x[9])
print(x[10])

In [ ]:
pred_mask[:20]

In [ ]:
print(_x[0])
print(_x[1])

In [ ]:
print(f"size of x\t\t: {x.shape}")
print(f"size of pred_mask\t: {pred_mask.shape}")
print(f"size of _x\t\t: {_x.shape}")

In [ ]:
pred_mask.size()[0] == 8192

In [ ]:
x = x.t().masked_scatter(pred_mask, _x.t()).t()

In [ ]:
print(x[8])
print(x[9])
print(x[10])

In [ ]:
x.size()

In [ ]:
assert x.size()[0] == (8192, )